// Generated by gencpp from file odom/reset_odom.msg
// DO NOT EDIT!


#ifndef ODOM_MESSAGE_RESET_ODOM_H
#define ODOM_MESSAGE_RESET_ODOM_H

#include <ros/service_traits.h>


#include <odom/reset_odomRequest.h>
#include <odom/reset_odomResponse.h>


namespace odom
{

struct reset_odom
{

typedef reset_odomRequest Request;
typedef reset_odomResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct reset_odom
} // namespace odom


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::odom::reset_odom > {
  static const char* value()
  {
    return "67113a69c2a17203e20c1586e4277dc3";
  }

  static const char* value(const ::odom::reset_odom&) { return value(); }
};

template<>
struct DataType< ::odom::reset_odom > {
  static const char* value()
  {
    return "odom/reset_odom";
  }

  static const char* value(const ::odom::reset_odom&) { return value(); }
};


// service_traits::MD5Sum< ::odom::reset_odomRequest> should match
// service_traits::MD5Sum< ::odom::reset_odom >
template<>
struct MD5Sum< ::odom::reset_odomRequest>
{
  static const char* value()
  {
    return MD5Sum< ::odom::reset_odom >::value();
  }
  static const char* value(const ::odom::reset_odomRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::odom::reset_odomRequest> should match
// service_traits::DataType< ::odom::reset_odom >
template<>
struct DataType< ::odom::reset_odomRequest>
{
  static const char* value()
  {
    return DataType< ::odom::reset_odom >::value();
  }
  static const char* value(const ::odom::reset_odomRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::odom::reset_odomResponse> should match
// service_traits::MD5Sum< ::odom::reset_odom >
template<>
struct MD5Sum< ::odom::reset_odomResponse>
{
  static const char* value()
  {
    return MD5Sum< ::odom::reset_odom >::value();
  }
  static const char* value(const ::odom::reset_odomResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::odom::reset_odomResponse> should match
// service_traits::DataType< ::odom::reset_odom >
template<>
struct DataType< ::odom::reset_odomResponse>
{
  static const char* value()
  {
    return DataType< ::odom::reset_odom >::value();
  }
  static const char* value(const ::odom::reset_odomResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ODOM_MESSAGE_RESET_ODOM_H
