// Generated by gencpp from file odom/rpm.msg
// DO NOT EDIT!


#ifndef ODOM_MESSAGE_RPM_H
#define ODOM_MESSAGE_RPM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace odom
{
template <class ContainerAllocator>
struct rpm_
{
  typedef rpm_<ContainerAllocator> Type;

  rpm_()
    : header()
    , rpm_fl(0.0)
    , rpm_fr(0.0)
    , rpm_rr(0.0)
    , rpm_rl(0.0)  {
    }
  rpm_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , rpm_fl(0.0)
    , rpm_fr(0.0)
    , rpm_rr(0.0)
    , rpm_rl(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _rpm_fl_type;
  _rpm_fl_type rpm_fl;

   typedef double _rpm_fr_type;
  _rpm_fr_type rpm_fr;

   typedef double _rpm_rr_type;
  _rpm_rr_type rpm_rr;

   typedef double _rpm_rl_type;
  _rpm_rl_type rpm_rl;





  typedef boost::shared_ptr< ::odom::rpm_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::odom::rpm_<ContainerAllocator> const> ConstPtr;

}; // struct rpm_

typedef ::odom::rpm_<std::allocator<void> > rpm;

typedef boost::shared_ptr< ::odom::rpm > rpmPtr;
typedef boost::shared_ptr< ::odom::rpm const> rpmConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::odom::rpm_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::odom::rpm_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::odom::rpm_<ContainerAllocator1> & lhs, const ::odom::rpm_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.rpm_fl == rhs.rpm_fl &&
    lhs.rpm_fr == rhs.rpm_fr &&
    lhs.rpm_rr == rhs.rpm_rr &&
    lhs.rpm_rl == rhs.rpm_rl;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::odom::rpm_<ContainerAllocator1> & lhs, const ::odom::rpm_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace odom

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::odom::rpm_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::odom::rpm_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::odom::rpm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::odom::rpm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::odom::rpm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::odom::rpm_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::odom::rpm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cb85f5cc617f2c19f53f5347bdd97298";
  }

  static const char* value(const ::odom::rpm_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcb85f5cc617f2c19ULL;
  static const uint64_t static_value2 = 0xf53f5347bdd97298ULL;
};

template<class ContainerAllocator>
struct DataType< ::odom::rpm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "odom/rpm";
  }

  static const char* value(const ::odom::rpm_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::odom::rpm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64 rpm_fl\n"
"float64 rpm_fr\n"
"float64 rpm_rr\n"
"float64 rpm_rl\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::odom::rpm_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::odom::rpm_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.rpm_fl);
      stream.next(m.rpm_fr);
      stream.next(m.rpm_rr);
      stream.next(m.rpm_rl);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct rpm_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::odom::rpm_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::odom::rpm_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "rpm_fl: ";
    Printer<double>::stream(s, indent + "  ", v.rpm_fl);
    s << indent << "rpm_fr: ";
    Printer<double>::stream(s, indent + "  ", v.rpm_fr);
    s << indent << "rpm_rr: ";
    Printer<double>::stream(s, indent + "  ", v.rpm_rr);
    s << indent << "rpm_rl: ";
    Printer<double>::stream(s, indent + "  ", v.rpm_rl);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ODOM_MESSAGE_RPM_H
