## *********************************************************
##
## File autogenerated for the odom package
## by the dynamic_reconfigure package.
## Please do not edit.
##
## ********************************************************/

from dynamic_reconfigure.encoding import extract_params

inf = float('inf')

config_description = {'upper': 'DEFAULT', 'lower': 'groups', 'srcline': 246, 'name': 'Default', 'parent': 0, 'srcfile': '/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py', 'cstate': 'true', 'parentname': 'Default', 'class': 'DEFAULT', 'field': 'default', 'state': True, 'parentclass': '', 'groups': [], 'parameters': [{'srcline': 291, 'description': 'Odometry method', 'max': 2147483647, 'cconsttype': 'const int', 'ctype': 'int', 'srcfile': '/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py', 'name': 'odom_mode', 'edit_method': "{'enum_description': 'Enum of methods', 'enum': [{'srcline': 10, 'description': 'Euler odometry', 'srcfile': '/home/gulce/project1/src/odom/cfg/parameters.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'Euler'}, {'srcline': 11, 'description': 'RK odometry', 'srcfile': '/home/gulce/project1/src/odom/cfg/parameters.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'RK'}]}", 'default': 0, 'level': 0, 'min': -2147483648, 'type': 'int'}, {'srcline': 291, 'description': 'Data for velocity calculation', 'max': 2147483647, 'cconsttype': 'const int', 'ctype': 'int', 'srcfile': '/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py', 'name': 'data_read', 'edit_method': "{'enum_description': 'Enum of data', 'enum': [{'srcline': 15, 'description': 'Velocity from ticks data', 'srcfile': '/home/gulce/project1/src/odom/cfg/parameters.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'Ticks'}, {'srcline': 16, 'description': 'Velocity from angular speed data', 'srcfile': '/home/gulce/project1/src/odom/cfg/parameters.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'RPM'}]}", 'default': 1, 'level': 1, 'min': -2147483648, 'type': 'int'}], 'type': '', 'id': 0}

min = {}
max = {}
defaults = {}
level = {}
type = {}
all_level = 0

#def extract_params(config):
#    params = []
#    params.extend(config['parameters'])
#    for group in config['groups']:
#        params.extend(extract_params(group))
#    return params

for param in extract_params(config_description):
    min[param['name']] = param['min']
    max[param['name']] = param['max']
    defaults[param['name']] = param['default']
    level[param['name']] = param['level']
    type[param['name']] = param['type']
    all_level = all_level | param['level']

parameters_Euler = 0
parameters_RK = 1
parameters_Ticks = 0
parameters_RPM = 1
